import PlanToThreeD from "./PlanToThreeD";
import ApiKeyBar from "./components/ApiKeyBar";

export default function Home() {
  return (
    <main className="mx-auto flex min-h-screen max-w-5xl flex-col gap-8 px-6 py-12">
      <header className="space-y-3">
        <span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-neutral-300">
          <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
          plan → 3D · powered by Nano Banana 2
        </span>
        <h1 className="text-4xl font-semibold tracking-tight">
          planto
          <span className="bg-gradient-to-r from-emerald-400 to-sky-400 bg-clip-text text-transparent">
            3d
          </span>
        </h1>
        <p className="max-w-2xl text-sm leading-relaxed text-neutral-400">
          Upload a 2D floor plan, set a style, and generate an axonometric
          overview — then turn any room into a photorealistic interior. The prompt
          is auto-written and fully editable; regenerate until you like it.
        </p>
      </header>
      <ApiKeyBar />
      <PlanToThreeD />
      <footer className="pt-4 text-center text-xs text-neutral-600">
        Images are generated by kie.ai · results are temporary — download what you
        want to keep.
      </footer>
    </main>
  );
}
